version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - mvn -B -f backend/pom.xml clean verify

artifacts:
  files:
    - backend/target/*.jar
    - infra/buildspec.yml
